CREATE TABLE IF NOT EXISTS supplier (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	phone VARCHAR(25),
	contractDate DATE NOT NULL DEFAULT CURRENT_DATE,
	observations TEXT
);

CREATE TABLE IF NOT EXISTS snacks (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	observations TEXT,
	price INTEGER 
);

CREATE TABLE IF NOT EXISTS orders (
	id SERIAL PRIMARY KEY,
	tableName SERIAL NOT NULL,
	dateOrder DATE NOT NULL DEFAULT CURRENT_DATE,
	situation VARCHAR(10) NOT NULL 
);

CREATE TABLE IF NOT EXISTS stockIngredients(
	id SERIAL PRIMARY KEY,
	name VARCHAR(255),
	category VARCHAR(10),
	quantity INTEGER
);